#!/bin/bash

# Deploy Production Frontend to greenpay.eywademo.cloud
# Replaces localhost:3000 with production domain

echo "🚀 Deploying Production Frontend..."
echo ""

SERVER="root@72.61.208.79"
REMOTE_DIR="/home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud"
BACKEND_DIR="$REMOTE_DIR/backend"

echo "📦 Build created successfully in dist/"
echo ""

echo "📋 Manual Deployment Steps:"
echo ""
echo "1️⃣  Upload dist/ folder contents to server:"
echo "    Local: /Users/nikolay/github/greenpay/dist/*"
echo "    Server: $REMOTE_DIR/"
echo ""
echo "    Via file manager:"
echo "    - Delete all files in $REMOTE_DIR (EXCEPT backend/ folder)"
echo "    - Upload all files from dist/ folder"
echo ""
echo "2️⃣  Update backend .env for production domain:"
echo "    ssh $SERVER"
echo "    cd $BACKEND_DIR"
echo "    nano .env"
echo ""
echo "    Change this line:"
echo "    PUBLIC_URL=http://localhost:3000"
echo ""
echo "    To:"
echo "    PUBLIC_URL=https://greenpay.eywademo.cloud"
echo ""
echo "3️⃣  Restart backend:"
echo "    pm2 restart greenpay-api"
echo ""
echo "4️⃣  Test the production site:"
echo "    Visit: https://greenpay.eywademo.cloud/buy-voucher"
echo "    Make a test purchase"
echo "    Email link should now use https://greenpay.eywademo.cloud"
echo ""
echo "📝 What Changed:"
echo "   ✓ Frontend now uses https://greenpay.eywademo.cloud/api"
echo "   ✓ Stripe checkout returns to production domain"
echo "   ✓ Email links use production domain"
echo "   ✓ All references to localhost:3000 removed"
echo ""
