#!/bin/bash

echo "=== Commands to investigate BSP payment rejection on server ==="
echo ""
echo "Copy and paste these commands in your SSH terminal (root@165.22.52.100):"
echo ""
echo "# 1. Check recent BSP payment API calls (last 200 lines)"
echo "pm2 logs greenpay-api --lines 200 | grep -i 'bsp\|doku\|payment\|card'"
echo ""
echo "# 2. Check for transaction failures in the last hour"
echo "pm2 logs greenpay-api --lines 500 | grep -i 'fail\|error\|reject'"
echo ""
echo "# 3. Monitor live logs while testing (run this BEFORE attempting payment)"
echo "pm2 logs greenpay-api --lines 50"
echo ""
echo "# 4. Check if there are any BSP API response codes logged"
echo "pm2 logs greenpay-api --lines 300 | grep -E '(status|code|response|4761|5573|4889)'"
echo ""
echo "# 5. Check backend error logs specifically"
echo "pm2 logs greenpay-api --err --lines 100"
echo ""
echo "# 6. Search for specific invoice from failed transaction"
echo "pm2 logs greenpay-api --lines 500 | grep -i 'PGKO-1767610715890'"
echo ""
echo "=== Database Investigation ==="
echo ""
echo "# 7. Check if failed transactions are recorded in database"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h 165.22.52.100 -U greenpay -d greenpay -c \\"
echo "  SELECT id, created_at, status, amount, payment_method, reference_number "
echo "  FROM transactions "
echo "  WHERE reference_number LIKE 'PGKO-1767610%' "
echo "  ORDER BY created_at DESC LIMIT 10;\\"
echo ""
echo "# 8. Check for any BSP-related error messages in transactions"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h 165.22.52.100 -U greenpay -d greenpay -c \\"
echo "  SELECT created_at, status, payment_method, notes "
echo "  FROM transactions "
echo "  WHERE created_at > NOW() - INTERVAL '2 hours' "
echo "  ORDER BY created_at DESC LIMIT 20;\\"
echo ""
echo "=== What to Look For ==="
echo ""
echo "In the logs, look for:"
echo "  - BSP API error responses (JSON with error codes)"
echo "  - HTTP status codes (400, 401, 403, 500, etc.)"
echo "  - 'GoBack' redirect messages"
echo "  - Card BIN validation messages"
echo "  - Mall ID configuration errors"
echo "  - Currency conversion errors"
echo ""
