import React, { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useToast } from '@/components/ui/use-toast';
import { verifyBSPPayment } from '@/lib/bspPaymentService';
import api from '@/lib/api/client';

/**
 * Public Purchase Payment Callback
 * Handles return from BSP payment gateway
 * Verifies payment and displays voucher codes
 */

const PublicPurchaseCallback = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const { toast } = useToast();

  const [state, setState] = useState('verifying'); // verifying, success, failed, error
  const [vouchers, setVouchers] = useState([]);
  const [paymentDetails, setPaymentDetails] = useState(null);
  const [errorMessage, setErrorMessage] = useState('');
  const [sessionData, setSessionData] = useState(null);

  useEffect(() => {
    verifyPaymentAndGenerateVouchers();
  }, []);

  const verifyPaymentAndGenerateVouchers = async () => {
    try {
      // Get parameters from URL - handle both Stripe and BSP formats
      const stripeSessionId = searchParams.get('session_id'); // Stripe format
      const status = searchParams.get('status');
      const merchantRef = searchParams.get('merchant_ref'); // BSP format
      const txnId = searchParams.get('txn_id');
      const authCode = searchParams.get('auth_code');
      const paymentMethod = searchParams.get('payment_method');
      const amount = searchParams.get('amount');
      const errorMsg = searchParams.get('error_message');

      console.log('Payment callback received:', {
        stripeSessionId,
        status,
        merchantRef,
        txnId,
        authCode,
        paymentMethod,
        amount
      });

      // Handle Stripe callback
      if (stripeSessionId) {
        console.log('Processing Stripe payment callback...');

        // Get our internal session ID from localStorage
        let internalSessionId = localStorage.getItem('purchase-session-id');

        // If not in localStorage, try to look it up by Stripe session ID
        if (!internalSessionId) {
          console.log('Session ID not in localStorage, looking up by Stripe session ID...');
          try {
            const lookupResponse = await api.get(`/public-purchases/session-by-stripe/${stripeSessionId}`);
            const lookupData = lookupResponse.data || lookupResponse;
            if (lookupData && lookupData.session && lookupData.session.id) {
              internalSessionId = lookupData.session.id;
              console.log('Found internal session ID:', internalSessionId);
            }
          } catch (error) {
            console.error('Could not lookup session by Stripe ID:', error);
          }
        }

        if (!internalSessionId) {
          throw new Error('Session ID is required');
        }

        // Show processing message
        setState('verifying');

        toast({
          title: "Payment Successful!",
          description: "Verifying payment and generating vouchers..."
        });

        // Poll the backend to check if vouchers were generated by webhook
        let attempts = 0;
        const maxAttempts = 10; // 10 attempts = ~30 seconds

        while (attempts < maxAttempts) {
          try {
            // Check if purchase session has vouchers
            const response = await api.get(`/public-purchases/session/${internalSessionId}`);

            console.log('Session API response:', response);

            // api.get() returns the parsed JSON directly (not wrapped in .data)
            // Handle both response formats: direct data or wrapped in data/success
            const sessionData = response.data || response;

            if (sessionData && sessionData.vouchers && sessionData.vouchers.length > 0) {
              // Vouchers found!
              setState('success');
              setVouchers(sessionData.vouchers);

              // Build payment details from session data
              const paymentInfo = {
                bspTransactionId: stripeSessionId,
                paymentMethod: 'Stripe',
                status: 'completed',
                amount: parseFloat(sessionData.session.amount) || 0,
                paymentDate: sessionData.session.completedAt || new Date().toISOString()
              };

              setPaymentDetails(paymentInfo);
              setSessionData(sessionData.session);

              toast({
                title: "Payment Complete!",
                description: `${sessionData.vouchers.length} voucher(s) generated successfully.`
              });

              // Clear stored session data
              localStorage.removeItem('purchase-session-id');
              localStorage.removeItem('purchase-session-data');

              return;
            } else {
              console.log(`Attempt ${attempts + 1}: Vouchers not ready yet, session status: ${sessionData?.session?.paymentStatus || 'unknown'}`);
            }
          } catch (error) {
            console.log(`Attempt ${attempts + 1}: API error -`, error.message);
          }

          // Wait 3 seconds before next attempt
          await new Promise(resolve => setTimeout(resolve, 3000));
          attempts++;
        }

        // If we get here, webhook might not have fired yet
        setState('success');
        toast({
          title: "Payment Received",
          description: "Your payment was successful. Voucher codes will be sent to your email/SMS shortly."
        });

        return;
      }

      // Check if payment was cancelled
      if (status === 'cancelled') {
        setState('failed');
        setErrorMessage('Payment was cancelled. No charges were made.');
        toast({
          variant: "destructive",
          title: "Payment Cancelled",
          description: "You can try again or contact support if you need help."
        });
        return;
      }

      // Check for immediate failure
      if (status === 'failed' || status === 'error') {
        setState('failed');
        setErrorMessage(errorMsg || 'Payment failed. Please try again.');
        toast({
          variant: "destructive",
          title: "Payment Failed",
          description: errorMessage
        });
        return;
      }

      // Verify payment with BSP (in production, this also verifies with BSP API)
      console.log('Verifying payment with BSP...');
      const verificationResult = await verifyBSPPayment(merchantRef, txnId);

      if (!verificationResult.success) {
        throw new Error('Payment verification failed');
      }

      console.log('Payment verified successfully:', verificationResult);

      // Complete purchase and generate vouchers
      console.log('Completing purchase session...');
      const response = await api.post('/public-purchases/complete', {
        sessionId: merchantRef,
        paymentData: {
          bspTransactionId: txnId,
          authCode: authCode,
          paymentMethod: paymentMethod || verificationResult.paymentMethod,
          cardLastFour: verificationResult.cardLastFour,
          paymentDate: verificationResult.paymentDate,
          status: 'completed'
        }
      });

      const result = response.data;
      console.log('Purchase completed:', result);

      // Set state for success display
      setState('success');
      setVouchers(result.vouchers || []);
      setPaymentDetails(verificationResult);
      setSessionData(result.session);

      toast({
        title: "Payment Successful!",
        description: `${result.vouchers?.length || 0} voucher(s) generated successfully.`
      });

      // Clear localStorage
      localStorage.removeItem('pending-purchase');
      localStorage.removeItem('purchase-session-id');
      localStorage.removeItem('purchase-session-data');

    } catch (error) {
      console.error('Payment verification error:', error);
      setState('error');
      setErrorMessage(error.message || 'An unexpected error occurred');
      toast({
        variant: "destructive",
        title: "Verification Error",
        description: error.message || 'Failed to verify payment. Please contact support.'
      });
    }
  };

  const handleDownloadVouchers = () => {
    // Generate text file with voucher codes
    const voucherText = vouchers.map((v, i) =>
      `Voucher ${i + 1}:\n` +
      `Code: ${v.voucher_code}\n` +
      `Amount: PGK ${v.amount}\n` +
      `Valid Until: ${new Date(v.valid_until).toLocaleDateString()}\n` +
      `Register at: ${window.location.origin}/register/${v.voucher_code}\n\n`
    ).join('---\n\n');

    const blob = new Blob([voucherText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PNG_Green_Fees_Vouchers_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Downloaded",
      description: "Voucher details saved to your device"
    });
  };

  const renderContent = () => {
    switch (state) {
      case 'verifying':
        return (
          <div className="text-center py-12">
            <div className="w-16 h-16 mx-auto mb-4 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
            <h2 className="text-2xl font-bold text-gray-800 mb-2">Verifying Payment...</h2>
            <p className="text-gray-600">Please wait while we confirm your payment with BSP Bank.</p>
            <p className="text-sm text-gray-500 mt-2">This usually takes a few seconds.</p>
          </div>
        );

      case 'success':
        return (
          <div className="py-8">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: 'spring', duration: 0.5 }}
              className="text-center mb-8"
            >
              <div className="text-8xl mb-4">✓</div>
              <h2 className="text-3xl font-bold text-green-700 mb-2">Payment Successful!</h2>
              <p className="text-gray-600 text-lg">Your voucher code(s) have been generated.</p>
            </motion.div>

            {/* Payment Details */}
            {paymentDetails && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-6">
                <h3 className="font-semibold text-green-900 mb-3">Payment Confirmation</h3>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between">
                    <span className="text-gray-600">Transaction ID:</span>
                    <span className="font-mono font-semibold">{paymentDetails.bspTransactionId}</span>
                  </div>
                  {paymentDetails.authCode && (
                    <div className="flex justify-between">
                      <span className="text-gray-600">Auth Code:</span>
                      <span className="font-mono">{paymentDetails.authCode}</span>
                    </div>
                  )}
                  <div className="flex justify-between">
                    <span className="text-gray-600">Amount Paid:</span>
                    <span className="font-bold text-green-700">PGK {paymentDetails.amount?.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Payment Method:</span>
                    <span className="font-semibold">
                      {paymentDetails.paymentMethod}
                      {paymentDetails.cardLastFour && ` •••• ${paymentDetails.cardLastFour}`}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-gray-600">Date:</span>
                    <span>{new Date(paymentDetails.paymentDate).toLocaleString()}</span>
                  </div>
                </div>
              </div>
            )}

            {/* Voucher Codes */}
            <div className="space-y-4 mb-6">
              <h3 className="font-semibold text-lg text-gray-800">Your Voucher Code(s):</h3>
              {vouchers.map((voucher, index) => (
                <motion.div
                  key={voucher.voucher_code}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <Card className="border-emerald-300 bg-gradient-to-r from-emerald-50 to-teal-50">
                    <CardContent className="p-6">
                      <div className="flex items-center justify-between mb-3">
                        <span className="text-sm font-semibold text-slate-600">
                          Voucher {index + 1} of {vouchers.length}
                        </span>
                        <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-xs font-semibold">
                          PAID
                        </span>
                      </div>
                      <div className="bg-white rounded-lg p-4 mb-3">
                        <p className="text-xs text-slate-500 mb-1">Voucher Code:</p>
                        <p className="text-2xl font-bold font-mono text-emerald-600 tracking-wider">
                          {voucher.voucher_code}
                        </p>
                      </div>
                      <div className="grid grid-cols-2 gap-3 text-sm">
                        <div>
                          <p className="text-slate-500">Value:</p>
                          <p className="font-semibold">PGK {voucher.amount}</p>
                        </div>
                        <div>
                          <p className="text-slate-500">Valid Until:</p>
                          <p className="font-semibold">{new Date(voucher.valid_until).toLocaleDateString()}</p>
                        </div>
                      </div>
                      <div className="mt-4 pt-4 border-t">
                        <p className="text-xs text-slate-600 mb-2">
                          📱 To register your passport:
                        </p>
                        <a
                          href={`/register/${voucher.voucher_code}`}
                          className="text-sm text-blue-600 hover:underline font-medium break-all"
                        >
                          {window.location.origin}/register/{voucher.voucher_code}
                        </a>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>

            {/* Delivery Confirmation */}
            {sessionData && (
              <Alert className="bg-blue-50 border-blue-200 mb-6">
                <AlertDescription className="text-blue-900">
                  <p className="font-semibold mb-2">📧 Voucher codes sent to:</p>
                  <ul className="text-sm space-y-1">
                    {sessionData.customerEmail && (
                      <li>📧 Email: {sessionData.customerEmail}</li>
                    )}
                    {sessionData.customerPhone && (
                      <li>📱 SMS: {sessionData.customerPhone}</li>
                    )}
                  </ul>
                  <p className="text-xs mt-2">
                    Check your inbox/messages. If not received within 5 minutes, please contact support.
                  </p>
                </AlertDescription>
              </Alert>
            )}

            {/* Action Buttons */}
            <div className="space-y-3">
              <Button
                onClick={handleDownloadVouchers}
                className="w-full bg-emerald-600 hover:bg-emerald-700"
                size="lg"
              >
                📥 Download Voucher Details
              </Button>
              <div className="grid grid-cols-2 gap-3">
                <Button
                  onClick={() => navigate(`/register/${vouchers[0]?.voucher_code}`)}
                  variant="outline"
                  size="lg"
                >
                  Register Passport Now
                </Button>
                <Button
                  onClick={() => navigate('/buy-voucher')}
                  variant="outline"
                  size="lg"
                >
                  Buy More Vouchers
                </Button>
              </div>
            </div>
          </div>
        );

      case 'failed':
        return (
          <div className="text-center py-12">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: 'spring', duration: 0.5 }}
              className="text-8xl mb-4 text-red-500"
            >
              ✗
            </motion.div>
            <h2 className="text-2xl font-bold text-red-700 mb-2">Payment Failed</h2>
            <p className="text-gray-600 mb-6">We couldn't process your payment.</p>

            {errorMessage && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-4 max-w-md mx-auto mb-6">
                <p className="text-sm text-red-800">{errorMessage}</p>
              </div>
            )}

            <div className="flex gap-4 justify-center">
              <Button
                onClick={() => navigate('/buy-voucher')}
                size="lg"
                className="bg-blue-600 hover:bg-blue-700"
              >
                Try Again
              </Button>
              <Button
                onClick={() => navigate('/')}
                variant="outline"
                size="lg"
              >
                Go Home
              </Button>
            </div>
          </div>
        );

      case 'error':
        return (
          <div className="text-center py-12">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: 'spring', duration: 0.5 }}
              className="text-8xl mb-4"
            >
              ⚠️
            </motion.div>
            <h2 className="text-2xl font-bold text-orange-700 mb-2">Verification Error</h2>
            <p className="text-gray-600 mb-6">We encountered an error while verifying your payment.</p>

            {errorMessage && (
              <div className="bg-orange-50 border border-orange-200 rounded-lg p-4 max-w-md mx-auto mb-6">
                <p className="text-sm text-orange-800">{errorMessage}</p>
              </div>
            )}

            <Alert className="bg-blue-50 border-blue-200 max-w-md mx-auto mb-6">
              <AlertDescription className="text-blue-800">
                <p className="text-sm">
                  Your payment may still be processing. Please check your email/SMS for voucher codes, or contact support.
                </p>
              </AlertDescription>
            </Alert>

            <div className="flex gap-4 justify-center">
              <Button
                onClick={() => verifyPaymentAndGenerateVouchers()}
                variant="outline"
                size="lg"
              >
                Retry Verification
              </Button>
              <Button
                onClick={() => navigate('/')}
                size="lg"
              >
                Contact Support
              </Button>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50 py-12 px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-3xl mx-auto"
      >
        <Card className="shadow-xl">
          <CardHeader className="bg-gradient-to-r from-emerald-500 to-teal-600 text-white">
            <CardTitle className="text-center text-2xl">
              {state === 'success' ? '🌿 Purchase Complete' : 'Payment Processing'}
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-6">
            {renderContent()}
          </CardContent>
        </Card>

        <div className="mt-6 text-center text-sm text-slate-500">
          <p>© 2025 PNG Green Fees System. All rights reserved.</p>
        </div>
      </motion.div>
    </div>
  );
};

export default PublicPurchaseCallback;
