#!/bin/bash

echo "=== Database Schema Investigation ==="
echo ""
echo "Copy these commands to check the actual table structure:"
echo ""
echo "# 1. Check transactions table columns"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  \\d transactions\\"
echo ""
echo "# 2. Check payment_sessions table columns"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  \\d payment_sessions\\"
echo ""
echo "# 3. Check buy_online_sessions table (likely where BSP sessions are stored)"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  \\d buy_online_sessions\\"
echo ""
echo "# 4. Find sessions by session_id pattern"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT * FROM buy_online_sessions "
echo "  WHERE session_id LIKE 'PGKO-1767610%' "
echo "  ORDER BY created_at DESC LIMIT 5;\\"
echo ""
echo "# 5. Alternative: Check all tables in the database"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT table_name FROM information_schema.tables "
echo "  WHERE table_schema = 'public' "
echo "  ORDER BY table_name;\\"
echo ""
