#!/bin/bash

echo "=== Correct Database Queries Based on Actual Schema ==="
echo ""
echo "# 1. Check payment_gateway_transactions for failed BSP payments"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT * FROM payment_gateway_transactions "
echo "  WHERE transaction_id LIKE 'PGKO-1767610%' "
echo "  ORDER BY created_at DESC LIMIT 10;\\"
echo ""
echo "# 2. Check individual_purchases (might contain Buy Online sessions)"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT * FROM individual_purchases "
echo "  WHERE created_at > NOW() - INTERVAL '2 hours' "
echo "  ORDER BY created_at DESC LIMIT 10;\\"
echo ""
echo "# 3. Check audit_logs for BSP payment events"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT * FROM audit_logs "
echo "  WHERE action ILIKE '%payment%' OR action ILIKE '%bsp%' OR action ILIKE '%doku%' "
echo "  ORDER BY created_at DESC LIMIT 20;\\"
echo ""
echo "# 4. Check email_logs for voucher emails (to find session IDs)"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT * FROM email_logs "
echo "  WHERE created_at > NOW() - INTERVAL '2 hours' "
echo "  ORDER BY created_at DESC LIMIT 10;\\"
echo ""
echo "# 5. First, check structure of payment_gateway_transactions table"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  \\d payment_gateway_transactions\\"
echo ""
echo "# 6. Check if there's a sessions or buy_online_sessions table (might be missed)"
echo "PGPASSWORD='GreenPay2025!Secure#PG' psql -h localhost -U greenpay_user -d greenpay_db -c \\"
echo "  SELECT table_name FROM information_schema.tables "
echo "  WHERE table_schema = 'public' AND table_name ILIKE '%session%' "
echo "  ORDER BY table_name;\\"
echo ""
