#!/bin/bash

# Deploy BSP Testing Endpoint (Webhook ISP Filter Bypass)
# This script helps you deploy the alternative testing endpoint for BSP DOKU

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  BSP DOKU Testing Endpoint Deployment                     ║"
echo "║  Alternative URL to bypass ISP filtering                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if backend/server.js has the changes
echo "✓ Checking local changes..."
if grep -q "doku-notify" backend/server.js; then
    echo "  ✓ Changes found in backend/server.js"
else
    echo "  ✗ ERROR: Changes not found in backend/server.js"
    echo "  Please ensure backend/server.js has been updated with the alias route"
    exit 1
fi

echo ""
echo "📦 File to deploy:"
echo "  • backend/server.js"
echo ""
echo "🎯 Deployment destination:"
echo "  /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/backend/server.js"
echo ""
echo "⚠️  MANUAL DEPLOYMENT REQUIRED:"
echo ""
echo "1. Open CloudPanel File Manager"
echo "2. Navigate to: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/backend/"
echo "3. Upload: backend/server.js"
echo ""
echo "4. Then paste these commands in your SSH terminal:"
echo ""
echo "   ssh root@165.22.52.100"
echo "   pm2 restart greenpay-api"
echo "   pm2 logs greenpay-api --lines 50"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 Testing after deployment:"
echo ""
echo "Test original webhook URL:"
echo "curl -X POST https://greenpay.eywademo.cloud/api/payment/webhook/doku/notify \\"
echo "  -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "  -d \"test=1\""
echo ""
echo "Expected: STOP"
echo ""
echo "Test new BSP testing URL:"
echo "curl -X POST https://greenpay.eywademo.cloud/api/payment/doku-notify/notify \\"
echo "  -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "  -d \"test=1\""
echo ""
echo "Expected: STOP"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📧 Share with BSP:"
echo ""
echo "Testing URL for BSP (bypasses ISP filters):"
echo "https://greenpay.eywademo.cloud/api/payment/doku-notify/notify"
echo ""
echo "Production URL (unchanged):"
echo "https://greenpay.eywademo.cloud/api/payment/webhook/doku/notify"
echo ""
echo "Full documentation: BSP_TESTING_ENDPOINT_SOLUTION.md"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Ready to deploy? Follow the manual steps above ⬆         ║"
echo "╚════════════════════════════════════════════════════════════╝"
