#!/bin/bash

##############################################################################
# PostgreSQL Automated Backup System for PNG Green Fees
#
# This script sets up:
# - Daily automated database backups
# - 30-day retention policy
# - Email notifications on failure
# - Cloud sync (optional)
#
# Usage: sudo ./setup-backups.sh
##############################################################################

set -e  # Exit on error

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   📦 PNG Green Fees - Backup System Setup                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Configuration
BACKUP_DIR="/var/backups/greenpay"
DB_NAME="greenpay"
DB_USER="postgres"
DB_HOST="localhost"
RETENTION_DAYS=30
LOG_FILE="/var/log/greenpay-backup.log"
NOTIFICATION_EMAIL="${NOTIFICATION_EMAIL:-admin@greenpay.gov.pg}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root (use sudo)"
  exit 1
fi

# Create backup directory
echo "📁 Creating backup directory..."
mkdir -p "$BACKUP_DIR"
chmod 700 "$BACKUP_DIR"
chown postgres:postgres "$BACKUP_DIR"
echo "   ✅ Created: $BACKUP_DIR"

# Create pre-deployment backup directory
mkdir -p "$BACKUP_DIR/pre-deploy"
chmod 700 "$BACKUP_DIR/pre-deploy"
chown postgres:postgres "$BACKUP_DIR/pre-deploy"

# Create monthly backup directory
mkdir -p "$BACKUP_DIR/monthly"
chmod 700 "$BACKUP_DIR/monthly"
chown postgres:postgres "$BACKUP_DIR/monthly"

# Create backup script
echo ""
echo "📝 Creating backup script..."
cat > /usr/local/bin/greenpay-backup.sh <<'BACKUP_SCRIPT'
#!/bin/bash
##############################################################################
# Daily Backup Script for PNG Green Fees Database
# Automatically generated by setup-backups.sh
##############################################################################

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DATE=$(date +%Y-%m-%d)
BACKUP_FILE="greenpay_backup_${TIMESTAMP}.sql.gz"
BACKUP_PATH="/var/backups/greenpay/${BACKUP_FILE}"
DB_NAME="greenpay"
DB_USER="postgres"
DB_HOST="localhost"
RETENTION_DAYS=30
LOG_FILE="/var/log/greenpay-backup.log"

# Log function
log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "========================================="
log "🚀 Starting database backup..."
log "   Database: $DB_NAME"
log "   File: $BACKUP_FILE"

# Create backup with compression
if sudo -u postgres pg_dump -h "$DB_HOST" "$DB_NAME" | gzip > "${BACKUP_PATH}"; then
  # Get backup size
  BACKUP_SIZE=$(du -h "${BACKUP_PATH}" | cut -f1)
  log "✅ Backup created successfully"
  log "   Size: $BACKUP_SIZE"
  log "   Location: ${BACKUP_PATH}"

  # Verify backup is not empty
  BACKUP_BYTES=$(stat -f%z "${BACKUP_PATH}" 2>/dev/null || stat -c%s "${BACKUP_PATH}" 2>/dev/null)
  if [ "$BACKUP_BYTES" -lt 1000 ]; then
    log "❌ ERROR: Backup file is too small (${BACKUP_BYTES} bytes)"
    echo "Backup file is suspiciously small: ${BACKUP_BYTES} bytes" | mail -s "GreenPay Backup WARNING" admin@greenpay.gov.pg
    exit 1
  fi

  # Upload to cloud storage (optional - uncomment and configure)
  # if command -v aws &> /dev/null; then
  #   log "☁️  Uploading to S3..."
  #   aws s3 cp "${BACKUP_PATH}" "s3://png-greenpay-backups/daily/${BACKUP_FILE}"
  #   if [ $? -eq 0 ]; then
  #     log "✅ Cloud backup uploaded"
  #   else
  #     log "⚠️  Cloud upload failed (local backup available)"
  #   fi
  # fi

  # Monthly backup (first day of month)
  if [ "$(date +%d)" == "01" ]; then
    MONTHLY_BACKUP="/var/backups/greenpay/monthly/greenpay_monthly_$(date +%Y%m).sql.gz"
    cp "${BACKUP_PATH}" "$MONTHLY_BACKUP"
    log "📅 Monthly backup created: $(basename $MONTHLY_BACKUP)"
  fi

  # Clean old backups (keep last 30 days)
  log "🧹 Cleaning old backups (older than $RETENTION_DAYS days)..."
  DELETED_COUNT=$(find /var/backups/greenpay -maxdepth 1 -name "greenpay_backup_*.sql.gz" -mtime +$RETENTION_DAYS -delete -print | wc -l)
  if [ "$DELETED_COUNT" -gt 0 ]; then
    log "   Deleted $DELETED_COUNT old backup(s)"
  else
    log "   No old backups to delete"
  fi

  # Keep monthly backups for 12 months
  find /var/backups/greenpay/monthly -name "greenpay_monthly_*.sql.gz" -mtime +365 -delete

  # Log current backup status
  TOTAL_BACKUPS=$(find /var/backups/greenpay -maxdepth 1 -name "greenpay_backup_*.sql.gz" | wc -l)
  TOTAL_SIZE=$(du -sh /var/backups/greenpay | cut -f1)
  log "📊 Backup Status:"
  log "   Total backups: $TOTAL_BACKUPS"
  log "   Total size: $TOTAL_SIZE"

  log "✅ Backup completed successfully"
  log "========================================="

else
  log "❌ BACKUP FAILED!"
  log "========================================="

  # Send alert email
  echo "Database backup failed on $(hostname) at $(date)" | mail -s "URGENT: GreenPay Backup FAILED" admin@greenpay.gov.pg

  exit 1
fi
BACKUP_SCRIPT

chmod +x /usr/local/bin/greenpay-backup.sh
chown root:root /usr/local/bin/greenpay-backup.sh
echo "   ✅ Created: /usr/local/bin/greenpay-backup.sh"

# Create pre-deployment backup script
echo ""
echo "📝 Creating pre-deployment backup script..."
cat > /usr/local/bin/greenpay-pre-deploy-backup.sh <<'PREDEPLOY_SCRIPT'
#!/bin/bash
##############################################################################
# Pre-Deployment Backup Script
# Run this before every deployment to create a restore point
##############################################################################

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="greenpay_pre_deploy_${TIMESTAMP}.sql.gz"
BACKUP_PATH="/var/backups/greenpay/pre-deploy/${BACKUP_FILE}"
DB_NAME="greenpay"
DB_USER="postgres"

echo "🔒 Creating pre-deployment backup..."

if sudo -u postgres pg_dump -h localhost "$DB_NAME" | gzip > "${BACKUP_PATH}"; then
  BACKUP_SIZE=$(du -h "${BACKUP_PATH}" | cut -f1)
  echo "✅ Pre-deployment backup created"
  echo "   File: ${BACKUP_FILE}"
  echo "   Size: ${BACKUP_SIZE}"
  echo ""
  echo "🎯 Safe to proceed with deployment"
  echo "   Restore command: gunzip -c ${BACKUP_PATH} | psql -U postgres ${DB_NAME}"

  # Keep only last 10 pre-deployment backups
  ls -t /var/backups/greenpay/pre-deploy/greenpay_pre_deploy_*.sql.gz | tail -n +11 | xargs -r rm

  exit 0
else
  echo "❌ Pre-deployment backup FAILED!"
  echo "⚠️  DO NOT PROCEED with deployment"
  exit 1
fi
PREDEPLOY_SCRIPT

chmod +x /usr/local/bin/greenpay-pre-deploy-backup.sh
chown root:root /usr/local/bin/greenpay-pre-deploy-backup.sh
echo "   ✅ Created: /usr/local/bin/greenpay-pre-deploy-backup.sh"

# Create restore script
echo ""
echo "📝 Creating restore script..."
cat > /usr/local/bin/greenpay-restore.sh <<'RESTORE_SCRIPT'
#!/bin/bash
##############################################################################
# Database Restore Script
# Usage: sudo greenpay-restore.sh [backup_file.sql.gz]
##############################################################################

if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root (use sudo)"
  exit 1
fi

BACKUP_FILE="$1"
DB_NAME="greenpay"
DB_USER="postgres"

if [ -z "$BACKUP_FILE" ]; then
  echo "📋 Available backups:"
  echo ""
  ls -lh /var/backups/greenpay/greenpay_backup_*.sql.gz | tail -10
  echo ""
  echo "Usage: sudo greenpay-restore.sh /var/backups/greenpay/greenpay_backup_YYYYMMDD_HHMMSS.sql.gz"
  exit 1
fi

if [ ! -f "$BACKUP_FILE" ]; then
  echo "❌ Backup file not found: $BACKUP_FILE"
  exit 1
fi

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   ⚠️  DATABASE RESTORE - DESTRUCTIVE OPERATION            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This will REPLACE the current database with:"
echo "   $(basename $BACKUP_FILE)"
echo "   $(ls -lh $BACKUP_FILE | awk '{print $5, $6, $7, $8}')"
echo ""
read -p "Are you sure? Type 'YES' to continue: " CONFIRM

if [ "$CONFIRM" != "YES" ]; then
  echo "❌ Restore cancelled"
  exit 1
fi

echo ""
echo "🛑 Stopping backend service..."
pm2 stop greenpay-api

echo ""
echo "💾 Creating safety backup before restore..."
SAFETY_BACKUP="/var/backups/greenpay/before_restore_$(date +%Y%m%d_%H%M%S).sql.gz"
sudo -u postgres pg_dump -h localhost "$DB_NAME" | gzip > "$SAFETY_BACKUP"
echo "   ✅ Safety backup: $(basename $SAFETY_BACKUP)"

echo ""
echo "🗑️  Dropping existing database..."
sudo -u postgres psql -c "DROP DATABASE IF EXISTS $DB_NAME;"

echo ""
echo "🆕 Creating fresh database..."
sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;"

echo ""
echo "📥 Restoring from backup..."
gunzip -c "$BACKUP_FILE" | sudo -u postgres psql "$DB_NAME"

if [ $? -eq 0 ]; then
  echo ""
  echo "✅ Database restored successfully!"
  echo ""
  echo "🔍 Verifying data..."
  PASSPORT_COUNT=$(sudo -u postgres psql -d "$DB_NAME" -t -c "SELECT COUNT(*) FROM \"Passport\";" | xargs)
  USER_COUNT=$(sudo -u postgres psql -d "$DB_NAME" -t -c "SELECT COUNT(*) FROM \"User\";" | xargs)
  echo "   Passports: $PASSPORT_COUNT"
  echo "   Users: $USER_COUNT"

  echo ""
  echo "🚀 Restarting backend service..."
  pm2 restart greenpay-api

  echo ""
  echo "✅ Restore completed successfully!"
  echo "   Safety backup available: $SAFETY_BACKUP"
else
  echo ""
  echo "❌ Restore FAILED!"
  echo "   Attempting to restore safety backup..."
  gunzip -c "$SAFETY_BACKUP" | sudo -u postgres psql "$DB_NAME"
  pm2 restart greenpay-api
  exit 1
fi
RESTORE_SCRIPT

chmod +x /usr/local/bin/greenpay-restore.sh
chown root:root /usr/local/bin/greenpay-restore.sh
echo "   ✅ Created: /usr/local/bin/greenpay-restore.sh"

# Create log file
touch "$LOG_FILE"
chmod 644 "$LOG_FILE"

# Setup cron job for daily backups
echo ""
echo "⏰ Configuring daily backup schedule..."

# Remove existing cron job if any
crontab -l 2>/dev/null | grep -v "greenpay-backup.sh" | crontab - 2>/dev/null || true

# Add new cron job (daily at 2 AM)
(crontab -l 2>/dev/null; echo "0 2 * * * /usr/local/bin/greenpay-backup.sh >> $LOG_FILE 2>&1") | crontab -

echo "   ✅ Cron job configured: Daily at 2:00 AM"

# Test backup immediately
echo ""
echo "🧪 Running initial backup test..."
/usr/local/bin/greenpay-backup.sh

if [ $? -eq 0 ]; then
  echo ""
  echo "╔════════════════════════════════════════════════════════════╗"
  echo "║   ✅ BACKUP SYSTEM SETUP COMPLETE                         ║"
  echo "╚════════════════════════════════════════════════════════════╝"
  echo ""
  echo "📋 Summary:"
  echo "   • Daily backups: 2:00 AM (automatic)"
  echo "   • Retention: 30 days"
  echo "   • Location: $BACKUP_DIR"
  echo "   • Log file: $LOG_FILE"
  echo ""
  echo "📝 Available commands:"
  echo "   • Manual backup:        sudo /usr/local/bin/greenpay-backup.sh"
  echo "   • Pre-deploy backup:    sudo /usr/local/bin/greenpay-pre-deploy-backup.sh"
  echo "   • Restore database:     sudo /usr/local/bin/greenpay-restore.sh [backup_file]"
  echo "   • View backup logs:     tail -f $LOG_FILE"
  echo "   • List backups:         ls -lh $BACKUP_DIR"
  echo ""
  echo "🔔 Next steps:"
  echo "   1. Configure email notifications (edit NOTIFICATION_EMAIL in scripts)"
  echo "   2. Setup cloud backup (uncomment AWS S3 section in backup script)"
  echo "   3. Test restore procedure monthly"
  echo ""
else
  echo ""
  echo "❌ Initial backup test failed!"
  echo "   Check permissions and database connection"
  echo "   Log file: $LOG_FILE"
  exit 1
fi
