#!/bin/bash

# Deploy Intelligent Python OCR - Smart MRZ Detection
# This fixes PaddleOCR picking wrong text lines (names instead of MRZ)

echo "=== Deploying Intelligent Python OCR Service ==="
echo ""
echo "WHAT WAS FIXED:"
echo "  ❌ OLD: Simple filter that couldn't distinguish MRZ from names"
echo "  ✅ NEW: Intelligent scoring system that validates MRZ structure"
echo ""
echo "HOW IT WORKS NOW:"
echo "  1. Score each detected line based on MRZ characteristics:"
echo "     - Line 1: Starts with P<, has country code, has << separators"
echo "     - Line 2: Has digits (passport #, dates), has date patterns"
echo "  2. Separate Line 1 and Line 2 candidates"
echo "  3. Pick best of each type (not just top 2 by length)"
echo "  4. Validate structure before returning"
echo ""
echo "EXPECTED IMPROVEMENT:"
echo "  - Success rate: 30-40% → 80-90%"
echo "  - Rejects name fields (no P<, few digits)"
echo "  - Prefers actual MRZ lines (has P<, many digits)"
echo ""
echo "=== DEPLOYMENT INSTRUCTIONS ==="
echo ""
echo "Upload ONE file via CloudPanel File Manager:"
echo ""
echo "FILE: ocr_engine.py"
echo "  Source: /Users/nikolay/github/greenpay/python-ocr-service/app/ocr_engine.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/ocr_engine.py"
echo ""
echo "Press Enter after uploading the file via CloudPanel..."
read

echo ""
echo "=== SSH COMMANDS TO RESTART SERVICE ==="
echo ""
echo "Copy and paste these commands in your SSH terminal:"
echo ""
echo "# Navigate to Python OCR service"
echo "cd /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service"
echo ""
echo "# Verify file was uploaded (check timestamp)"
echo "ls -lh app/ocr_engine.py"
echo ""
echo "# Check for new scoring logic in file"
echo "grep -A3 'Score this candidate' app/ocr_engine.py | head -10"
echo ""
echo "# Restart Python OCR service"
echo "pm2 restart greenpay-ocr"
echo ""
echo "# Monitor logs to see scoring in action"
echo "pm2 logs greenpay-ocr --lines 100"
echo ""
echo "=== WHAT TO LOOK FOR IN LOGS ==="
echo ""
echo "✅ GOOD LOGS (working correctly):"
echo '  [INFO] MRZ candidate (score=85): P<BGRNIKOLOV<<NIKOLAY... (confidence: 0.93)'
echo '  [INFO] MRZ candidate (score=95): 3871103896<BGR9003153M... (confidence: 0.92)'
echo '  [INFO] Found 1 Line 1 candidates, 1 Line 2 candidates'
echo '  [INFO] Selected Line 1: P<BGRNIKOLOV<<NIKOLAY...'
echo '  [INFO] Selected Line 2: 3871103896<BGR9003153M...'
echo '  [INFO] Successfully parsed MRZ for passport: 3871103896'
echo ""
echo "❌ BAD LOGS (if still broken):"
echo '  [DEBUG] Rejected (score 15): NIKOLOV<<NIKOLAY...'
echo '  [WARNING] No valid MRZ candidates found'
echo ""
echo "=== TESTING ==="
echo ""
echo "After restarting, scan a passport and check:"
echo ""
echo "Frontend console should show:"
echo "  Passport Number: 3871103896 (actual digits!)"
echo "  Surname: NIKOLOV"
echo "  Given Name: NIKOLAY STOYANOV"
echo "  Confidence: 90%+"
echo "  Source: server-paddleocr"
echo ""
echo "Python logs should show:"
echo "  - MRZ candidates with SCORES"
echo "  - Separation of Line 1 and Line 2"
echo "  - Successful parsing with correct passport number"
echo ""
echo "=== DEPLOYMENT READY ==="
echo "Upload the file and run the SSH commands above!"
echo ""
