#!/bin/bash

# Deploy Python OCR with Enhanced Debug Logging
# This will show us EXACTLY what PaddleOCR detects and what gets parsed

echo "=== Deploying Python OCR Debug Logging ==="
echo ""
echo "WHAT THIS ADDS:"
echo "  1. Shows ALL text lines detected by PaddleOCR"
echo "  2. Shows scoring for each candidate"
echo "  3. Shows Line 1 and Line 2 selection"
echo "  4. Shows field-by-field parsing with positions"
echo ""
echo "THIS WILL HELP US SEE:"
echo "  - What text PaddleOCR is actually reading"
echo "  - Which lines get high scores vs low scores"
echo "  - If Line 1 and Line 2 are swapped"
echo "  - If field positions are correct (surname, nationality, dates)"
echo ""
echo "=== FILES TO UPLOAD ===
"
echo ""
echo "FILE 1: ocr_engine.py (shows PaddleOCR detection)"
echo "  Source: /Users/nikolay/github/greenpay/python-ocr-service/app/ocr_engine.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/ocr_engine.py"
echo ""
echo "FILE 2: mrz_parser.py (shows field parsing)"
echo "  Source: /Users/nikolay/github/greenpay/python-ocr-service/app/mrz_parser.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/mrz_parser.py"
echo ""
echo "Press Enter after uploading BOTH files via CloudPanel..."
read

echo ""
echo "=== SSH COMMANDS ==="
echo ""
echo "# Restart Python OCR service"
echo "pm2 restart greenpay-ocr"
echo ""
echo "# Monitor logs"
echo "pm2 logs greenpay-ocr --lines 200"
echo ""
echo "=== WHAT TO LOOK FOR IN LOGS ==="
echo ""
echo "After scanning a passport, you should see:"
echo ""
echo "1. PaddleOCR Detection:"
echo "   === PADDLEOCR DETECTED 5 TEXT LINES ==="
echo "   Line 1: 'REPUBLIKA BULGARIA' (confidence: 0.95)"
echo "   Line 2: 'NIKOLOV, NIKOLAY STOYANOV' (confidence: 0.96)"
echo "   Line 3: 'P<BGRNIKOLOV<<NIKOLAY<STOYANOV' (confidence: 0.93)"
echo "   Line 4: '3871103896<BGR9003153M3109073' (confidence: 0.92)"
echo "   Line 5: 'PP 3871103896' (confidence: 0.94)"
echo ""
echo "2. Scoring:"
echo "   [INFO] MRZ candidate (score=110): P<BGRNIKOLOV..."
echo "   [INFO] MRZ candidate (score=95): 3871103896<BGR..."
echo "   [DEBUG] Rejected (score=5): REPUBLIKA..."
echo "   [DEBUG] Rejected (score=15): NIKOLOV..."
echo ""
echo "3. Line Selection:"
echo "   [INFO] Found 1 Line 1 candidates, 1 Line 2 candidates"
echo "   [INFO] Selected Line 1: P<BGRNIKOLOV<<NIKOLAY..."
echo "   [INFO] Selected Line 2: 3871103896<BGR9003153M..."
echo ""
echo "4. Field Parsing:"
echo "   === PARSING MRZ ==="
echo "   Line 1 (44 chars): P<BGRNIKOLOV<<NIKOLAY<STOYANOV<<<<<<<<<"
echo "   Line 2 (44 chars): 3871103896<BGR9003153M3109073<<<<<<<<<<<<"
echo "   Issuing Country (pos 2-5): 'BGR'"
echo "   Names raw (pos 5-44): 'NIKOLOV<<NIKOLAY<STOYANOV'"
echo "   Parsed Surname: 'NIKOLOV'"
echo "   Parsed Given Name: 'NIKOLAY STOYANOV'"
echo "   Passport Number (pos 0-9): '3871103896'"
echo "   Nationality (pos 10-13): 'BGR'"
echo "   DOB raw (pos 13-19): '900315'"
echo "   Sex (pos 20): 'M'"
echo "   Expiry raw (pos 21-27): '310907'"
echo ""
echo "=== NOW TEST IT ==="
echo "1. Upload the files"
echo "2. Restart greenpay-ocr"
echo "3. Scan a passport"
echo "4. Look at the logs"
echo "5. Share the complete log output so we can diagnose the issue!"
echo ""
