#!/bin/bash

# Deploy Name Splitting Heuristic Fix
# Fixes merged given names issue: 'NIKOLAYSTOYANOV' → 'NIKOLAY STOYANOV'

echo "=== Deploying Name Splitting Fix ===="
echo ""
echo "WHAT THIS FIXES:"
echo "  Problem: Surname contains all names, given name is empty"
echo "  Cause:   OCR reads 'NIKOLOV<NIKOLAYSTOYANOV' instead of 'NIKOLOV<<NIKOLAY<STOYANOV'"
echo "  Fix:     Heuristic detection and intelligent splitting of merged given names"
echo ""
echo "=== FILE TO UPLOAD VIA CLOUDPANEL ==="
echo ""
echo "Source:      /Users/nikolay/github/greenpay/python-ocr-service/app/mrz_parser.py"
echo "Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/mrz_parser.py"
echo ""
echo "Press Enter after uploading file via CloudPanel..."
read

echo ""
echo "=== PASTE THESE COMMANDS IN YOUR SSH TERMINAL ==="
echo ""
echo "# 1. Verify file uploaded (check timestamp is recent)"
echo "ls -lh /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/mrz_parser.py"
echo ""
echo "# 2. Verify heuristic fix is present"
echo "grep -A2 'HEURISTIC FIX' /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/mrz_parser.py"
echo ""
echo "# 3. Restart Python OCR service"
echo "pm2 restart greenpay-ocr"
echo ""
echo "# 4. Monitor logs in real-time"
echo "pm2 logs greenpay-ocr --lines 100"
echo ""
echo "=== EXPECTED LOG OUTPUT AFTER SCANNING ==="
echo ""
echo "✅ GOOD (fix working):"
echo "   [MRZ_PARSER] Names raw (pos 5-44): 'NIKOLOV<NIKOLAYSTOYANOV<<<<...'"
echo "   [MRZ_PARSER] Found << separator at position 23"
echo "   [MRZ_PARSER] Heuristic split applied: surname=NIKOLOV, merged_given=NIKOLAYSTOYANOV, split_given=NIKOLAY STOYANOV"
echo "   [MRZ_PARSER] Parsed Surname: 'NIKOLOV'"
echo "   [MRZ_PARSER] Parsed Given Name: 'NIKOLAY STOYANOV'"
echo "   [MRZ_PARSER] Passport Number (pos 0-9): '3871103896'"
echo "   [MRZ_PARSER] Nationality (pos 10-13): 'BGR'"
echo "   [MRZ_PARSER] DOB raw (pos 13-19): '690927'"
echo "   [MRZ_PARSER] Successfully parsed MRZ for passport: 3871103896"
echo ""
echo "Frontend should show:"
echo "   Passport Number: 3871103896"
echo "   Surname: NIKOLOV"
echo "   Given Name: NIKOLAY STOYANOV  ← FIXED!"
echo "   Nationality: BGR"
echo "   Date of Birth: 1969-09-27"
echo "   Sex: M"
echo "   Expiry: 2025-09-17"
echo ""
echo "❌ BAD (if heuristic not triggered):"
echo "   [MRZ_PARSER] Parsed Surname: 'NIKOLOV NIKOLAY STOYANOV'"
echo "   [MRZ_PARSER] Parsed Given Name: ''"
echo ""
echo "=== TEST PROCEDURE ==="
echo "1. Upload mrz_parser.py via CloudPanel File Manager"
echo "2. Paste verification commands in SSH terminal"
echo "3. Restart greenpay-ocr"
echo "4. Scan a passport in the web app"
echo "5. Watch PM2 logs for heuristic split message"
echo "6. Verify form auto-fills with correct name fields"
echo ""
