#!/bin/bash

# CRITICAL FIX: Remove Destructive OCR Corrections
# Problem: Python service was replacing ALL 0->O and 1->I, destroying passport numbers
# Solution: Minimal corrections - only replace spaces with '<'

echo "=== CRITICAL Python OCR Fix - Remove Destructive Corrections ==="
echo ""
echo "PROBLEM FOUND:"
echo "  - ocr_engine.py was converting ALL 0->O and 1->I"
echo "  - mrz_parser.py was doing aggressive field-specific corrections"
echo "  - Result: Passport numbers destroyed (e.g., '1234567' became 'I234567')"
echo ""
echo "FIX APPLIED:"
echo "  - Removed blanket 0->O and 1->I replacements"
echo "  - Only replace spaces with '<' separators"
echo "  - Trust PaddleOCR's raw output (it's accurate!)"
echo ""
echo "=== DEPLOYMENT INSTRUCTIONS ==="
echo ""
echo "You need to upload TWO files via CloudPanel File Manager:"
echo ""
echo "FILE 1: ocr_engine.py"
echo "  Source: /Users/nikolay/github/greenpay/python-ocr-service/app/ocr_engine.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/ocr_engine.py"
echo ""
echo "FILE 2: mrz_parser.py"
echo "  Source: /Users/nikolay/github/greenpay/python-ocr-service/app/mrz_parser.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/mrz_parser.py"
echo ""
echo "Press Enter after uploading both files via CloudPanel..."
read

echo ""
echo "=== SSH COMMANDS TO RESTART SERVICE ==="
echo ""
echo "Copy and paste these commands in your SSH terminal:"
echo ""
echo "# Navigate to Python OCR service"
echo "cd /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service"
echo ""
echo "# Verify files were uploaded (check timestamps)"
echo "ls -lh app/ocr_engine.py app/mrz_parser.py"
echo ""
echo "# Restart the Python OCR service"
echo "pm2 restart greenpay-ocr"
echo ""
echo "# Monitor logs"
echo "pm2 logs greenpay-ocr --lines 50"
echo ""
echo "=== TESTING ==="
echo ""
echo "After restarting, scan a passport and check logs for:"
echo ""
echo "✅ GOOD: Passport numbers with actual digits (e.g., '3871103896')"
echo "❌ BAD: Passport numbers with letters replacing digits (e.g., 'PBGRNIKOL')"
echo ""
echo "Frontend should show:"
echo "  Passport Number: 3871103896 (actual digits, not letters!)"
echo "  Confidence: 90%+"
echo "  Source: server-paddleocr"
echo ""
echo "=== DEPLOYMENT READY ==="
echo "Upload the files and run the SSH commands above!"
echo ""
