#!/bin/bash

# Deploy BSP DOKU Webhook with Voucher Creation
# Adds voucher creation logic to webhook handler after successful payment

echo "=========================================="
echo "BSP DOKU Webhook - Voucher Creation Fix"
echo "=========================================="
echo ""
echo "This deployment adds voucher creation to the BSP DOKU webhook handler."
echo "After successful payment, the webhook will now:"
echo "  1. Update transaction status"
echo "  2. Create passport record (if needed)"
echo "  3. Generate voucher code and barcode"
echo "  4. Create voucher in individual_purchases table"
echo "  5. Send email notification to customer"
echo ""

# File to deploy
FILE="backend/routes/payment-webhook-doku.js"

echo "File to upload: $FILE"
echo ""
echo "=========================================="
echo "MANUAL DEPLOYMENT INSTRUCTIONS"
echo "=========================================="
echo ""
echo "1. Open CloudPanel File Manager"
echo "   URL: https://your-cloudpanel-url/filemanager"
echo ""
echo "2. Navigate to:"
echo "   /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/backend/routes/"
echo ""
echo "3. Upload the following file:"
echo "   - payment-webhook-doku.js (from: $FILE)"
echo ""
echo "4. After upload, paste these commands in your SSH terminal:"
echo ""
echo "   # Verify file was uploaded"
echo "   cd /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/backend/routes/"
echo "   ls -lh payment-webhook-doku.js"
echo "   echo \"\""
echo ""
echo "   # Restart backend"
echo "   pm2 restart greenpay-api"
echo "   echo \"\""
echo ""
echo "   # Monitor logs"
echo "   pm2 logs greenpay-api --lines 50"
echo ""
echo "=========================================="
echo "TESTING INSTRUCTIONS"
echo "=========================================="
echo ""
echo "After BSP confirms webhook URLs are configured:"
echo ""
echo "1. Make a test payment at:"
echo "   https://greenpay.eywademo.cloud/public/buy"
echo ""
echo "2. Monitor webhook logs in real-time:"
echo "   pm2 logs greenpay-api --lines 100 | grep DOKU"
echo ""
echo "3. Expected log sequence:"
echo "   [DOKU NOTIFY] Webhook received"
echo "   [DOKU NOTIFY] Signature verified successfully"
echo "   [DOKU NOTIFY] Transaction updated successfully"
echo "   [DOKU NOTIFY] Payment successful - creating voucher"
echo "   [DOKU VOUCHER] Starting voucher creation"
echo "   [DOKU VOUCHER] Generated voucher code: XXXXXXXX"
echo "   [DOKU VOUCHER] Created voucher: XXXXXXXX"
echo "   [DOKU VOUCHER] Updated session as completed"
echo "   [DOKU VOUCHER] Sending email notification"
echo "   [DOKU VOUCHER] ✅ Voucher creation completed successfully"
echo "   [DOKU NOTIFY] ✅ Voucher created successfully: XXXXXXXX"
echo "   [DOKU NOTIFY] Responding with CONTINUE"
echo ""
echo "4. Check database to verify voucher was created:"
echo "   PGPASSWORD='GreenPay2025!Secure#PG' psql -h 165.22.52.100 -U greenpay -d greenpay \\"
echo "     -c \"SELECT voucher_code, passport_number, amount, payment_method, customer_email FROM individual_purchases ORDER BY created_at DESC LIMIT 1;\""
echo ""
echo "5. Customer should see voucher immediately on success page"
echo "   (no more 20-second timeout waiting for voucher)"
echo ""
echo "=========================================="
echo "WHAT THIS FIXES"
echo "=========================================="
echo ""
echo "BEFORE:"
echo "  ❌ Webhook only updated transaction status"
echo "  ❌ No voucher created"
echo "  ❌ Success page timed out after 20 seconds"
echo "  ❌ Confusing error message for customer"
echo ""
echo "AFTER:"
echo "  ✅ Webhook creates voucher immediately after payment"
echo "  ✅ Success page shows voucher within 2 seconds"
echo "  ✅ Customer receives email with voucher"
echo "  ✅ Proper error handling (still returns CONTINUE to DOKU)"
echo ""
echo "=========================================="
echo "FILES CHANGED"
echo "=========================================="
echo ""
echo "backend/routes/payment-webhook-doku.js:"
echo "  - Added voucher creation imports (QRCode, JsBarcode, voucherConfig)"
echo "  - Added generateBarcodeDataURL() helper function"
echo "  - Added createVoucherFromPayment() function (mirrors buy-online.js logic)"
echo "  - Updated notify webhook to call voucher creation on success"
echo "  - Idempotent (prevents duplicate vouchers if webhook retries)"
echo "  - Transaction-safe (uses BEGIN/COMMIT/ROLLBACK)"
echo ""
echo "=========================================="
echo "READY TO DEPLOY"
echo "=========================================="
echo ""
echo "File location: $(pwd)/$FILE"
echo ""
echo "Upload this file to CloudPanel, then restart PM2."
echo ""
