#!/bin/bash

# Deploy OCR Line 1 Detection Fix
# Fixes Line 1/Line 2 swap issue when OCR reads P<BGR as PBGR

echo "=== Deploying Line 1 Detection Fix ===="
echo ""
echo "CRITICAL ISSUE FOUND IN LATEST SCAN:"
echo "  OCR read:  'PBGRNIKOLOV<<NIKOLAY<STOYANOV'  (missing < after P)"
echo "  Should be: 'P<BGRNIKOLOV<<NIKOLAY<STOYANOV'"
echo ""
echo "WHAT WENT WRONG:"
echo "  1. OCR missed the separator after P: PBGR instead of P<BGR"
echo "  2. Line 1 detection checks for .startswith('P<') - FAILED"
echo "  3. Line 1 scored only 60 points (no P< bonus of +50)"
echo "  4. Not recognized as Line 1"
echo "  5. Line 1 and Line 2 got SWAPPED"
echo "  6. Parser tried to extract passport number from name field!"
echo ""
echo "THE FIX:"
echo "  1. Detect PBGR pattern (P + 3 letters) as likely Line 1"
echo "  2. Give it high score (+45 points)"
echo "  3. Classify as Line 1 candidate"
echo "  4. Insert missing < after P during normalization"
echo ""
echo "=== FILES TO UPLOAD VIA CLOUDPANEL ==="
echo ""
echo "FILE 1: ocr_engine.py"
echo "  Source:      /Users/nikolay/github/greenpay/python-ocr-service/app/ocr_engine.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/ocr_engine.py"
echo ""
echo "FILE 2: mrz_parser.py (name splitting fix)"
echo "  Source:      /Users/nikolay/github/greenpay/python-ocr-service/app/mrz_parser.py"
echo "  Destination: /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/mrz_parser.py"
echo ""
echo "Press Enter after uploading BOTH files via CloudPanel..."
read

echo ""
echo "=== PASTE THESE COMMANDS IN YOUR SSH TERMINAL ==="
echo ""
echo "# 1. Verify files uploaded"
echo "ls -lh /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/*.py"
echo ""
echo "# 2. Verify PBGR pattern detection"
echo "grep -A2 'likely P<BGR' /home/eywademo-greenpay/htdocs/greenpay.eywademo.cloud/python-ocr-service/app/ocr_engine.py"
echo ""
echo "# 3. Restart service"
echo "pm2 restart greenpay-ocr"
echo ""
echo "# 4. Monitor logs"
echo "pm2 logs greenpay-ocr --lines 100"
echo ""
echo "=== EXPECTED LOG OUTPUT (FIXED) ==="
echo ""
echo "✅ CORRECT (Line 1 detected properly):"
echo ""
echo "   [OCR_ENGINE] Line 12: 'PBGRNIKOLOV<<NIKOLAY<STOYANOV' (confidence: 0.87)"
echo "   [OCR_ENGINE] Line 13: '38711038968GR6909275M250917...' (confidence: 0.96)"
echo ""
echo "   [OCR_ENGINE] MRZ candidate (score=110): PBGRNIKOLOV<<NIKOLAY... ← HIGH SCORE!"
echo "   [OCR_ENGINE] MRZ candidate (score=85): 38711038968GR..."
echo ""
echo "   [OCR_ENGINE] Found 1 Line 1 candidates, 1 Line 2 candidates  ← CORRECT!"
echo "   [OCR_ENGINE] Selected Line 1: PBGRNIKOLOV<<NIKOLAY..."
echo "   [OCR_ENGINE] Selected Line 2: 38711038968GR6909275M..."
echo ""
echo "   [OCR_ENGINE] Fixed Line 1 format: inserted < after P"
echo "   [OCR_ENGINE] Found nationality code 'BGR' at position 10"
echo "   [OCR_ENGINE] Fixed Line 2 format: removed 1 chars, inserted < at pos 9"
echo ""
echo "   [MRZ_PARSER] === PARSING MRZ ==="
echo "   [MRZ_PARSER] Line 1 (44 chars): P<BGRNIKOLOV<<NIKOLAY<STOYANOV<<<  ← FIXED!"
echo "   [MRZ_PARSER] Line 2 (44 chars): 387110389<BGR6909275M250917...  ← FIXED!"
echo ""
echo "   [MRZ_PARSER] Found << separator at position 7"
echo "   [MRZ_PARSER] Heuristic split applied: original='NIKOLAYSTOYANOV', split='NIKOLAY STOYANOV'"
echo ""
echo "   [MRZ_PARSER] Parsed Surname: 'NIKOLOV'"
echo "   [MRZ_PARSER] Parsed Given Name: 'NIKOLAY STOYANOV'  ← FIXED!"
echo "   [MRZ_PARSER] Passport Number: '387110389'  ← FIXED!"
echo "   [MRZ_PARSER] Nationality: 'BGR'  ← FIXED!"
echo "   [MRZ_PARSER] DOB: '690927'  ← FIXED!"
echo "   [MRZ_PARSER] Sex: 'M'  ← FIXED!"
echo "   [MRZ_PARSER] Expiry: '250917'  ← FIXED!"
echo ""
echo "Frontend auto-fill:"
echo "  ✅ Passport Number: 387110389"
echo "  ✅ Surname: NIKOLOV"
echo "  ✅ Given Name: NIKOLAY STOYANOV"
echo "  ✅ Nationality: BGR"
echo "  ✅ Date of Birth: 1969-09-27"
echo "  ✅ Sex: M"
echo "  ✅ Expiry: 2025-09-17"
echo ""
echo "=== SUMMARY OF ALL FIXES IN THIS DEPLOYMENT ==="
echo "1. ✅ Detect PBGR pattern as Line 1 (missing < after P)"
echo "2. ✅ Insert missing < after P during normalization"
echo "3. ✅ Search for nationality codes to handle 8GR → BGR"
echo "4. ✅ Split merged given names (NIKOLAYSTOYANOV → NIKOLAY STOYANOV)"
echo ""
echo "This should make PaddleOCR work reliably!"
echo ""
